#!/usr/local/bin/python

from cgi import *

form = FormContent()
date = form["date"][0]

print 'Content-type: text/html\n\n'
print '<HTML><HEAD><TITLE>Severe Weather Forecasting Tips</TITLE></HEAD><BODY BACKGROUND="gifs/clouds.jpg"><br>'
print '<CENTER><FONT COLOR="#000000"><FONT SIZE=+4>Here Are Some Helpful Tips For Forecasting Severe Weather</FONT></FONT></CENTER><br>'
print '<TABLE><CENTER><TR><TD VALIGN=TOP WIDTH="30%"><UL><IMG SRC="gifs/torn.jpg" ALIGN=CENTER></TD>'
print '</TR></TABLE></CENTER><CENTER></CENTER><br><br>'
print '<CENTER><FONT COLOR="#000000"><FONT SIZE=+2>This Page Is Intended To Help High School Students Forecast Severe Weather</FONT></FONT></CENTER>'
print '<br><br><br><P><ALIGN=LEFT><B><FONT COLOR="#FF0000"><FONT SIZE=+2>Here Is Some Information You Should Know Before Forecasting</FONT></FONT></B>'
print '<BR>&nbsp;<TABLE><TR><TD VALIGN=TOP WIDTH="40%"><UL><ALIGN=TAB><LI><FONT SIZE=+1>The surface map shows conditions at the surface.</FONT></LI>'
print '<P><ALIGN=TAB><LI><FONT SIZE=+1>The 850 mb map shows conditions at 5,000 feet above sea level.</FONT></LI>'
print '<P><ALIGN=TAB><LI><FONT SIZE=+1>The 500 mb map shows conditions at 18,000 feet above sea level.</FONT></LI>'
print '<P><ALIGN=TAB><LI><FONT SIZE=+1>An upper air sounding is data taken from a weather balloon sent up twice each day.</FONT></LI></UL></TD>'
print '</TR></TABLE>&nbsp;<br><br><P><IMG SRC="gifs/lightning2.gif"></P><br>'
print '<P><ALIGN=LEFT><B><FONT COLOR="#FF0000"><FONT SIZE=+2>Steps</FONT></FONT></B>'
print '<P><ALIGN=LEFT><LI><FONT COLOR="#000000"><FONT SIZE=+2>1. Look at'
print 'Surface Map For:</FONT></FONT></LI><br>'
print '<BR><FONT COLOR="#000000"><FONT SIZE=+2></FONT></FONT><TABLE><TR><TD VALIGN=TOP WIDTH="40%">'
print '<UL><ALIGN=TAB><LI><FONT SIZE=+1><A HREF="fronts.html">Fronts </A>in the Area</FONT></LI>'
print '<BR><FONT SIZE=+1></FONT><P><ALIGN=TAB><LI>'
print '<FONT SIZE=+1><A HREF="gradients.html">Temperature Gradients</A></FONT></LI>'
print '<P><ALIGN=TAB><LI><FONT SIZE=+1><A HREF="dewpoints.html">Dew Point </A>Levels</FONT></LI>'
print '<BR><FONT SIZE=+1></FONT><P><ALIGN=TAB><LI><FONT SIZE=+1><A HREF="wind.html">Wind Speed and Direction</A></FONT></LI>'
print '</UL></TD></TR></TABLE>&nbsp;<br><br><P><ALIGN=LEFT><LI><FONT COLOR="#000000"><FONT SIZE=+2>2. Look at'
print '850 mb Map For:</FONT></FONT></LI><br>'
print '<TABLE><TR><TD VALIGN=TOP WIDTH="40%"><UL><ALIGN=TAB><br><LI>'
print '<FONT SIZE=+1><A HREF="advection.html">Advection'
print 'of Moisture</A></FONT></LI>'
print '</UL></TD></TR></TABLE>&nbsp;<P><ALIGN=LEFT><LI>'
print '<FONT COLOR="#000000"><FONT SIZE=+2>3. Look at 500 mb Map With Vorticity For:</FONT></FONT></LI>'
print '<br><TABLE><TR><TD VALIGN=TOP WIDTH="60%"><UL><ALIGN=TAB><br><LI>'
print '<FONT SIZE=+1><A HREF="pva.html">Positive Vorticity Advection</A></FONT></LI>'
print '</UL></TD></TR></TABLE>&nbsp;<BR>&nbsp;<P><ALIGN=LEFT><LI>'
print '<FONT COLOR="#000000"><FONT SIZE=+2>4. Look at Upper'
print 'Air Soundings For:</FONT></FONT></LI><br><TABLE><TR><TD VALIGN=TOP WIDTH="40%"><UL><ALIGN=TAB>'
print '<br><LI><FONT SIZE=+1><A HREF="li.html">Lifted Index</A></FONT></LI>'
print '<P><ALIGN=TAB><LI><FONT SIZE=+1><A HREF="cape.html">Cape</A></FONT></LI><P><ALIGN=TAB><LI>'
print '<FONT SIZE=+1><A HREF="windshear.html">Wind Shear</A></FONT></LI>'
print '</UL></TD></TR></TABLE>&nbsp;<BR>&nbsp;<P><ALIGN=LEFT><LI>'
print '<FONT COLOR="#000000"><FONT SIZE=+2>5. Complete Your <A HREF="'+date+'main.html">Forecast</A></FONT></LI></P><br><br><br>'
print '<P><ALIGN=LEFT><B><FONT COLOR="#FF0000"><FONT SIZE=+2>Here Are Some Helpful Weather Product Links</FONT></B></FONT>'
print '<BR>&nbsp;<TABLE><TR><TD><UL><ALIGN=TAB><LI>'
print '<FONT SIZE=+1><A HREF="'+date+'data.html">Weather Products Page</A></FONT></LI>'
print '<P><ALIGN=TAB><LI></TD></TR></TABLE>&nbsp;</BODY></HTML>'

